routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/tasks','TaskController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use Illuminate\Http\Request;
use Session;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::orderBy('id','desc')->get();
        return view('tasks.index')-> with('tasksData',$tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'taskName' => 'required|min:5|max:255'
        ]);

        $task = new Task;
        $task -> name = $request-> taskName;
        $task -> save();

        Session::flash('addSuccess',"Task has been added successfuly");

        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        return view("tasks.edit")->with('task',$task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $task->name = $request->newTaskName;
        $task->save();
        Session::flash('editSuccess',"task have been edited successfully");

        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $task->delete();
        Session::flash('deleteSuccess',"Task has been deleted successfuly");
        return redirect()->route('tasks.index');
    }
}

resources/views/tasks/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<title>To-do list</title>
</head>
<body>
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			
			<div class="row">
				
				<h2>to-do List</h2>

			</div>

			<div class="row">
				<form action="{{ route("tasks.update",["tasks"=>"$task->id"]) }}" method="POST">

					{{ csrf_field() }}

					<input type="hidden" name="_method" value="PUT">
					<div class="col-md-8">
						<input type="text" name="newTaskName" class="form-control" value="{{ $task->name }}">
					</div>

					<div class="col-md-4">
						<input type="submit" class="btn btn-primary btn-block" value="Edit">
					</div>	

				</form>
		
			</div>

		</div>
	</div>
</body>
</html>

resources/views/tasks/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<title>To-do list</title>
</head>
<body>
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			

			<div class="row">
				
				<h2>to-do List</h2>
				@if(Session::has('addSuccess'))

				<div class="alert alert-success">
					<strong>Success</strong> {{Session::get("addSuccess")}}
				</div>
				@elseif(Session::has('deleteSuccess'))
				<div class="alert alert-success">
					<strong>Success</strong> {{Session::get("deleteSuccess")}}
				</div>
				
				@elseif(Session::has('editSuccess'))

					<div class="alert alert-success">
						<strong>Success</strong> {{Session::get("editSuccess")}}
					</div>
				@endif

				

				@if(count($errors) > 0)
					<div class="alert alert-danger">
						<ul>
						@foreach($errors->all() as $error)

							<li>{{$error}}</li>

						@endforeach
						</ul>
					</div>
				@endif
			</div>

			<div class="row">
				<form action="{{ route("tasks.store") }}" method="POST">
					{{ csrf_field() }}

					<div class="col-md-8">
						<input type="text" name="taskName" class="form-control" id="">
					</div>

					<div class="col-md-4">
						<input type="submit" class="btn btn-primary btn-block" value="submit">
					</div>	

				</form>
		
			</div>
			<div class="row">

				@if(count($tasksData) > 0 )
					<table class="table">
						<thead>
							<th>Tasks {{count($tasksData)}}</th>
							<th>name</th>
							<th>edit</th>
							<th>delete</th>

						</thead>
						<tbody>
							@foreach($tasksData as $taskData)
							<tr>
								<td>{{$taskData->id}}</td>
								<td>{{$taskData->name}}</td>
								<td><a href="{{ route("tasks.edit",["tasks"=>"$taskData->id"]) }}" class="btn btn-default">Edit</a></td>
								<td>
									<form action="{{ route("tasks.destroy",["tasks"=>"$taskData->id"]) }}" method="POST">
										{{ csrf_field()}}
										<input type="hidden" name="_method" value="DELETE" >
										<input type="submit" value="delete" class="btn btn-danger">
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				@endif

			</div>
		</div>
	</div>
</body>
</html>